apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-lib-claim
  namespace: immich 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn