apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
spec:
  secretName: argocd-server-tls
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
  - "argocd.lan"
  issuerRef:
    name:  spnw-intermediate-ca1-issuer
    kind: ClusterIssuer