apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
spec:
  template:
    spec:
      initContainers:
        - image: busybox:1.36
          name: wait-for-postgres
          command:
            - sh
            - -c
            - |
              until nc -z homelab-pg-rw.infra.svc.cluster.local 5432; do
                echo "waiting for postgres…"
                sleep 1
              done
