apiVersion: v1
data:
  ACCESS_KEY_ID: R0s5NThkNGU3OGNlODI5NjE0YTBjZGNmMjY=
  ACCESS_SECRET_KEY: OGIyMDQ2M2QzMzQzYThkOWFlNzZmNjY4MWMwYjg0NWNiYjg4NjRjY2IxOTMxZDBlNDc2MTMwOTFmMjRkZTBmZg==
  REGION: Z2FyYWdl
kind: Secret
metadata:
  name: garage-cnpg-backup-secret
