apiVersion: v1
data:
  ACCESS_KEY_ID: R0s4MDFiZWM1ZDRkNDY5ZTc0MDc5MjcyZmU=
  ACCESS_SECRET_KEY: YTc5ZmRkMmVjNzA0ZjJkM2JhODBhNmIyNWQ3NDFiYzc1NGRkMzI1ZjNhZGQ5NDFiZjczNWRjZjIxZGFiZWRjNw==
  REGION: Z2FyYWdl
kind: Secret
metadata:
  name: garage-cnpg-backup-secret
